apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserver-control
rules:
- apiGroups: ["", "agones.dev", "allocation.agones.dev"]
  resources: ["pods", "gameserverallocations", "gameservers"]
  verbs: ["get", "list", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gladiators-service
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
