apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: gladiators-matchgame
  namespace: gladiators-gameserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: gladiators-matchgame # 標示為gladiators-matchgame, 方便之後對版本做刪除等管理
        imgVersion: "0.1.360" # 加版本標籤, 未來方便針對某個版本進行移除也要連agones產生的gameserver一起移除, 版本必須要跟image版本一致
    spec:
      ports:
      - name: default
        containerPort: 7654
        portPolicy: Dynamic
        protocol: TCPUDP
      # server健康檢查參數, 可參考官方文件: https://agones.dev/site/docs/guides/health-checking/ 官方配置: https://github.com/googleforgames/agones/blob/release-1.36.0/examples/gameserver.yaml
      health:
        disabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      template:
        metadata:
          labels:
            type: gladiators-matchgame # 標示為gladiators-matchgame, 方便之後對版本做刪除等管理
            imgVersion: "0.1.360" # 加版本標籤, 未來方便針對某個版本的pods進行移除, 版本必須要跟image版本一致避免搞混
        spec:
          containers:
          - name: gladiators-matchgame
            image: asia-east1-docker.pkg.dev/mygladiators-dev/gladiators/gladiators-matchgame:0.1.360
            resources:
              requests:
                memory: "32Mi"
                cpu: "10m"
              limits:
                memory: "64Mi"
                cpu: "20m"
            env:
            - name: ImgVer
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['imgVersion']
            - name: NodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "Mode"
              value: "standard" # 一般模式
            - name: "PORT"
              value: "7654"
            - name: "Version"
              value: "Dev"
            # mongodb相關
            - name: MongoAPIPublicKey
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MongoAPIPublicKey
            - name: MongoAPIPrivateKey
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MongoAPIPrivateKey
            - name: MongoUser
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MongoUser
            - name: MongoPW
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MongoPW