apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: gladiators-gameserver
subjects:
- kind: ServiceAccount
  name: default
  namespace: gladiators-gameserver
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
