apiVersion: v1
kind: Service
metadata:
  name: gladiators-matchmaker
  namespace: gladiators-service
  labels:
    app: gladiators-matchmaker
spec:
  type: LoadBalancer
  selector:
    app: gladiators-matchmaker
  ports:
    - protocol: TCP
      port: 32680
      targetPort: 30390
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gladiators-matchmaker
  namespace: gladiators-service
spec:
  selector:
    matchLabels:
      app: gladiators-matchmaker
  replicas: 1
  template:
    metadata:
      labels:
        app: gladiators-matchmaker
    spec:
      serviceAccountName: default # 指定使用default serviceAccount
      containers:
      - name: gladiators-matchmaker
        image: asia-east1-docker.pkg.dev/fourth-waters-410202/gladiators/gladiators-matchmaker:0.2.8
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
        env:
        - name: ImgVer
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['imgVersion']
        - name: "PORT"
          value: "30390"
        - name: "Env"
          value: "Dev"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        # mongodb相關
        - name: MongoAPIPublicKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPublicKey
        - name: MongoAPIPrivateKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPrivateKey
        - name: MongoUser
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoUser
        - name: MongoPW
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoPW
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gladiators-matchmaker-autoscaler
  namespace: gladiators-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gladiators-matchmaker
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
