# 讓herofishing-matchserver有控制herofishing-gameserver節點的權限
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gameserver-control-binding
  namespace: gladiators-gameserver  
subjects:
- kind: ServiceAccount
  name: default
  namespace: gladiators-service
roleRef:
  kind: ClusterRole
  name: gameserver-control
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: gladiators-service
subjects:
- kind: ServiceAccount
  name: default
  namespace: gladiators-service
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
