// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: matchgrpc.proto

package matchgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MatchService_MatchComm_FullMethodName = "/matchgrpc.MatchService/MatchComm"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServiceClient interface {
	// Bi-directional streaming RPC for match communication
	MatchComm(ctx context.Context, opts ...grpc.CallOption) (MatchService_MatchCommClient, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) MatchComm(ctx context.Context, opts ...grpc.CallOption) (MatchService_MatchCommClient, error) {
	stream, err := c.cc.NewStream(ctx, &MatchService_ServiceDesc.Streams[0], MatchService_MatchComm_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &matchServiceMatchCommClient{stream}
	return x, nil
}

type MatchService_MatchCommClient interface {
	Send(*MatchRequest) error
	Recv() (*MatchResponse, error)
	grpc.ClientStream
}

type matchServiceMatchCommClient struct {
	grpc.ClientStream
}

func (x *matchServiceMatchCommClient) Send(m *MatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *matchServiceMatchCommClient) Recv() (*MatchResponse, error) {
	m := new(MatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility
type MatchServiceServer interface {
	// Bi-directional streaming RPC for match communication
	MatchComm(MatchService_MatchCommServer) error
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatchServiceServer struct {
}

func (UnimplementedMatchServiceServer) MatchComm(MatchService_MatchCommServer) error {
	return status.Errorf(codes.Unimplemented, "method MatchComm not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_MatchComm_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatchServiceServer).MatchComm(&matchServiceMatchCommServer{stream})
}

type MatchService_MatchCommServer interface {
	Send(*MatchResponse) error
	Recv() (*MatchRequest, error)
	grpc.ServerStream
}

type matchServiceMatchCommServer struct {
	grpc.ServerStream
}

func (x *matchServiceMatchCommServer) Send(m *MatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *matchServiceMatchCommServer) Recv() (*MatchRequest, error) {
	m := new(MatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchgrpc.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MatchComm",
			Handler:       _MatchService_MatchComm_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "matchgrpc.proto",
}
