apiVersion: apps/v1
kind: Deployment
metadata:
  name: gladiators-crontasker
  namespace: gladiators-service
spec:
  selector:
    matchLabels:
      app: gladiators-crontasker
  replicas: 1
  template:
    metadata:
      labels:
        app: gladiators-crontasker
        type: gladiators-crontasker  # 標示為gladiators-service, 方便之後對版本做刪除等管理
        imgVersion: "0.1.15"       # 加版本標籤, 未來方便針對某個版本進行移除也要連agones產生的gameserver一起移除, 版本必須要跟image版本一致
    spec:
      containers:
      - name: gladiators-crontasker
        image: asia-east1-docker.pkg.dev/fourth-waters-410202/gladiators/gladiators-crontasker:0.1.15
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
        # 環境變數設定
        env:
        - name: "Env"
          value: "Dev"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name              
        # mongodb相關
        - name: MongoAPIPublicKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPublicKey
        - name: MongoAPIPrivateKey
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoAPIPrivateKey
        - name: MongoUser
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoUser
        - name: MongoPW
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MongoPW